ARG LIBERTY_IMAGE=open-liberty
ARG LIBERTY_TAG=kernel-slim

FROM maven:3-ibmjava-8 AS builder

ARG DAYTRADER_TAG="master"
ENV DAYTRADER_TAG=${DAYTRADER_TAG}

# Download, Checkout and Build Day Trader
RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/* \
    && git clone https://github.com/OpenLiberty/sample.daytrader8 && cd sample.daytrader8/ && git checkout ${DAYTRADER_TAG} \
    && mvn clean package

# Main Container
FROM ${LIBERTY_IMAGE}:${LIBERTY_TAG}

# Set ARG used in COPY
ARG OPT_PATH=ol

# Setting Day Trader & WLP Enviroment Variables
ENV OPT_PATH=${OPT_PATH}
ENV contextRoot=daytrader
ENV MAX_USERS=1000
ENV MAX_QUOTES=500

# DB2 Enviroment Variables
ENV DB_HOST=
ENV DB_PORT=
ENV DB_NAME=trade
ENV DB_USERNAME=
ENV DB_PASSWORD=

# Config Files from Builder
COPY --from=builder --chown=1001:0 /sample.daytrader8/src/main/liberty/config/bootstrap.properties /config/bootstrap.properties
COPY --from=builder --chown=1001:0 /sample.daytrader8/target/io.openliberty.sample.daytrader8.war /config/apps/

# DB2 Config Files
COPY --from=builder --chown=1001:0 /sample.daytrader8/src/main/liberty/config/server.xml_db2 /config/server.xml
RUN mkdir /config/db2jars && ln -s /config/db2jars /opt/${OPT_PATH}/wlp/usr/shared/resources/db2jars

# Install Any Addtional Liberties Needed
RUN configure.sh

EXPOSE 9080 9443

CMD ["server", "run", "defaultServer"]